version: "3.9"
services:
  frontend:
    container_name: frontend
    restart: on-failure
    image: 201800726/u-social_frontend
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
